services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=loudAl@rm15
      - SECRET_KEY=d584a5ded027698197372364a94ab6448355a2c3e2306461f97632b0549ddcaf
    command: gunicorn -b 0.0.0.0:5000 app:app
    depends_on:
      - neo4j

  neo4j:
    build:
      context: .
      dockerfile: Dockerfile-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/loudAl@rm15

volumes:
  neo4j_data:
  neo4j_logs: